modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "wynnrunner"
version = "${version}"
displayName = "WynnRunner"
authors = "Fis-chl"
description = '''

'''
#logoFile = ""

[[dependencies.wynnrunner]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wynnrunner]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "wynnrunner.mixins.json"
